import { AppShell, TopBar } from '@/components/layout/app-shell';
import { Card } from '@/components/ui/card';

const SECTIONS = [
  {
    title: 'What we collect',
    body: 'Your Telegram profile basics (ID, name, username, language), the photos you upload, the facial attributes and numeric face signature we derive from them, the content you generate and your purchases.',
  },
  {
    title: 'Why',
    body: 'Only to create and improve your mascot and its content, process Telegram Stars payments, prevent abuse and provide support. We never sell your data and never use it for identification or advertising profiles.',
  },
  {
    title: 'Face data (biometrics)',
    body: 'Processing requires your explicit consent at first upload. Source photos are deleted automatically after 30 days. The derived Mascot DNA stays with your mascot until you delete it or your account.',
  },
  {
    title: 'AI providers',
    body: 'Images and videos are generated by vetted AI providers under data-processing agreements that prohibit training on your content.',
  },
  {
    title: 'Your rights',
    body: 'Delete a mascot anytime, or your entire account from Profile → Delete account (erasure completes within minutes; payment records are retained anonymised as required by law).',
  },
  {
    title: 'Age',
    body: 'Mascot AI is for users aged 16+. Photos of minors and other people without their consent are not allowed.',
  },
  {
    title: 'Payments & refunds',
    body: 'Digital goods are sold for Telegram Stars. Failed generations are refunded automatically. For other issues use /paysupport in the bot.',
  },
];

export default function LegalPage() {
  return (
    <AppShell tabs={false}>
      <TopBar title="Terms & Privacy" subtitle="Plain-language summary" />
      <div className="space-y-2.5">
        {SECTIONS.map((s) => (
          <Card key={s.title} className="p-4">
            <h2 className="text-[14px] font-semibold">{s.title}</h2>
            <p className="mt-1 text-[13px] leading-relaxed text-muted">{s.body}</p>
          </Card>
        ))}
      </div>
    </AppShell>
  );
}
