/**
 * Sticker emotions (60+). Each emotion maps to a Telegram emoji (required by the Bot API for
 * every sticker), a scene description for the prompt compiler and a base emotion used by
 * reduced renderers (SVG fallback, meme classifier).
 */
export const STICKER_EMOTIONS = [
  'happy',
  'laughing',
  'crying',
  'angry',
  'shocked',
  'love',
  'sigma',
  'cool',
  'thinking',
  'facepalm',
  'joy',
  'rofl',
  'wink',
  'kiss',
  'shy',
  'embarrassed',
  'nervous',
  'scared',
  'terrified',
  'disgusted',
  'sick',
  'sleepy',
  'sleeping',
  'yawning',
  'bored',
  'confused',
  'suspicious',
  'smug',
  'proud',
  'celebrate',
  'excited',
  'starstruck',
  'mindblown',
  'sad',
  'disappointed',
  'pleading',
  'grateful',
  'shrug',
  'eyeroll',
  'annoyed',
  'furious',
  'evil',
  'crazy',
  'silly',
  'yummy',
  'money',
  'dead',
  'dizzy',
  'cold',
  'hot',
  'shush',
  'salute',
  'peace',
  'ok',
  'thumbsdown',
  'clap',
  'hug',
  'bye',
  'idea',
  'gasp',
  'oops',
  'party',
] as const;

export type StickerEmotion = (typeof STICKER_EMOTIONS)[number];

/** The original ten emotions every renderer supports natively. */
export const BASE_EMOTIONS = ['happy', 'laughing', 'crying', 'angry', 'shocked', 'love', 'sigma', 'cool', 'thinking', 'facepalm'] as const;
export type BaseEmotion = (typeof BASE_EMOTIONS)[number];

export interface EmotionRecipe {
  key: StickerEmotion;
  label: string;
  emoji: string;
  /** Extra emojis Telegram uses to suggest the sticker (max 20 total). */
  extraEmojis: string[];
  expression: string;
  pose: string;
  /** Optional graphic accent rendered by the model around the character. */
  accent?: string;
  /** Closest of the original ten (SVG fallback renderer, meme classifier). */
  base: BaseEmotion;
}

export const EMOTION_CATALOG: Record<StickerEmotion, EmotionRecipe> = {
  happy: {
    key: 'happy',
    label: 'Happy',
    emoji: '😊',
    extraEmojis: ['🙂', '😄'],
    expression: 'warm genuine smile with eyes slightly squinting',
    pose: 'waving hello with one hand',
    base: 'happy',
  },
  laughing: {
    key: 'laughing',
    label: 'Laughing',
    emoji: '😂',
    extraEmojis: ['🤣', '😆'],
    expression: 'laughing out loud, mouth wide open, eyes shut, tears of joy',
    pose: 'leaning back holding belly',
    accent: 'small comic "HA" motion lines',
    base: 'laughing',
  },
  crying: {
    key: 'crying',
    label: 'Crying',
    emoji: '😭',
    extraEmojis: ['😢', '🥲'],
    expression: 'dramatic crying, big streams of cartoon tears, trembling lips',
    pose: 'shoulders slumped, arms hanging',
    accent: 'tear droplets',
    base: 'crying',
  },
  angry: {
    key: 'angry',
    label: 'Angry',
    emoji: '😡',
    extraEmojis: ['😠', '🤬'],
    expression: 'furious frown, furrowed brows, gritted teeth, red cheeks',
    pose: 'clenched fists raised',
    accent: 'cartoon steam puffs',
    base: 'angry',
  },
  shocked: {
    key: 'shocked',
    label: 'Shocked',
    emoji: '😱',
    extraEmojis: ['😮', '🤯'],
    expression: 'jaw dropped, eyes wide, eyebrows raised high',
    pose: 'both hands on cheeks',
    accent: 'surprise burst lines',
    base: 'shocked',
  },
  love: {
    key: 'love',
    label: 'Love',
    emoji: '😍',
    extraEmojis: ['❤️', '🥰'],
    expression: 'dreamy smile with heart-shaped eyes, blushing',
    pose: 'making a heart shape with both hands',
    accent: 'floating hearts',
    base: 'love',
  },
  sigma: {
    key: 'sigma',
    label: 'Sigma',
    emoji: '🗿',
    extraEmojis: ['😏', '💪'],
    expression: 'confident smirk, one eyebrow raised, unbothered gaze',
    pose: 'arms crossed, slight head tilt, three-quarter view',
    base: 'sigma',
  },
  cool: {
    key: 'cool',
    label: 'Cool',
    emoji: '😎',
    extraEmojis: ['🤙', '🔥'],
    expression: 'relaxed cool smile wearing stylish sunglasses',
    pose: 'thumbs up',
    base: 'cool',
  },
  thinking: {
    key: 'thinking',
    label: 'Thinking',
    emoji: '🤔',
    extraEmojis: ['🧐', '💭'],
    expression: 'pondering, eyes looking up, pursed lips',
    pose: 'hand on chin',
    accent: 'small thought bubble with question mark',
    base: 'thinking',
  },
  facepalm: {
    key: 'facepalm',
    label: 'Facepalm',
    emoji: '🤦',
    extraEmojis: ['😩', '🙄'],
    expression: 'exasperated, eyes closed',
    pose: 'palm covering forehead and upper face, mouth still visible',
    base: 'facepalm',
  },
  joy: {
    key: 'joy',
    label: 'Tears of joy',
    emoji: '🥹',
    extraEmojis: ['😂', '😊'],
    expression: 'laughing so hard that happy tears roll down, eyes squeezed shut',
    pose: 'holding belly with both hands',
    accent: 'joy tear droplets',
    base: 'laughing',
  },
  rofl: {
    key: 'rofl',
    label: 'ROFL',
    emoji: '🤣',
    extraEmojis: ['😂', '😆'],
    expression: 'rolling with laughter, head tilted far to the side, mouth wide open',
    pose: 'clutching belly, leaning sideways',
    accent: 'motion lines',
    base: 'laughing',
  },
  wink: {
    key: 'wink',
    label: 'Wink',
    emoji: '😉',
    extraEmojis: ['😜', '😏'],
    expression: 'playful smile with one eye closed in a wink',
    pose: 'finger gun pointing at the viewer',
    base: 'happy',
  },
  kiss: {
    key: 'kiss',
    label: 'Kiss',
    emoji: '😘',
    extraEmojis: ['💋', '😚'],
    expression: 'puckered lips blowing a kiss, one eye closed, blushing',
    pose: 'hand at the lips blowing a kiss',
    accent: 'small flying heart',
    base: 'love',
  },
  shy: {
    key: 'shy',
    label: 'Shy',
    emoji: '☺️',
    extraEmojis: ['😊', '🙈'],
    expression: 'bashful little smile, eyes looking down, strong blush',
    pose: 'hands clasped together in front of the chest',
    accent: 'blush lines on the cheeks',
    base: 'happy',
  },
  embarrassed: {
    key: 'embarrassed',
    label: 'Embarrassed',
    emoji: '😅',
    extraEmojis: ['😬', '🙃'],
    expression: 'awkward wobbly smile, blushing, a drop of sweat',
    pose: 'scratching the back of the head',
    accent: 'sweat drop',
    base: 'happy',
  },
  nervous: {
    key: 'nervous',
    label: 'Nervous',
    emoji: '😬',
    extraEmojis: ['😰', '😥'],
    expression: 'nervous wavy mouth, eyebrows tilted up, sweating',
    pose: 'fidgeting hands together at the chest',
    accent: 'sweat drops',
    base: 'shocked',
  },
  scared: {
    key: 'scared',
    label: 'Scared',
    emoji: '😨',
    extraEmojis: ['😰', '🫣'],
    expression: 'frightened wide eyes, trembling mouth',
    pose: 'both hands raised defensively near the face',
    accent: 'shiver lines',
    base: 'shocked',
  },
  terrified: {
    key: 'terrified',
    label: 'Terrified',
    emoji: '😱',
    extraEmojis: ['😨', '👻'],
    expression: 'screaming in terror, pale face, eyes huge',
    pose: 'hands pressed to the cheeks',
    accent: 'shock lines',
    base: 'shocked',
  },
  disgusted: {
    key: 'disgusted',
    label: 'Disgusted',
    emoji: '🤢',
    extraEmojis: ['😖', '🤮'],
    expression: 'grimace of disgust, nose wrinkled, eyes squinting',
    pose: 'one palm pushed forward saying no',
    base: 'angry',
  },
  sick: {
    key: 'sick',
    label: 'Sick',
    emoji: '🤒',
    extraEmojis: ['🤧', '😷'],
    expression: 'queasy greenish face, frowning, droopy eyes',
    pose: 'holding the stomach',
    base: 'crying',
  },
  sleepy: {
    key: 'sleepy',
    label: 'Sleepy',
    emoji: '😪',
    extraEmojis: ['🥱', '😴'],
    expression: 'half-closed heavy eyelids, tiny yawn',
    pose: 'arms hanging loosely',
    accent: 'floating Z letters',
    base: 'facepalm',
  },
  sleeping: {
    key: 'sleeping',
    label: 'Sleeping',
    emoji: '😴',
    extraEmojis: ['💤', '🛌'],
    expression: 'fast asleep, eyes closed, relaxed mouth',
    pose: 'head nodding forward, arms hanging',
    accent: 'floating Z letters',
    base: 'facepalm',
  },
  yawning: {
    key: 'yawning',
    label: 'Yawning',
    emoji: '🥱',
    extraEmojis: ['😪', '😴'],
    expression: 'huge yawn with mouth wide open, eyes shut',
    pose: 'hand covering the yawning mouth',
    base: 'shocked',
  },
  bored: {
    key: 'bored',
    label: 'Bored',
    emoji: '😑',
    extraEmojis: ['🙄', '😐'],
    expression: 'unimpressed half-lidded stare, flat mouth',
    pose: 'chin resting on a hand',
    base: 'thinking',
  },
  confused: {
    key: 'confused',
    label: 'Confused',
    emoji: '😕',
    extraEmojis: ['🤨', '❓'],
    expression: 'one eyebrow raised, wavy unsure mouth',
    pose: 'scratching the head',
    accent: 'question mark',
    base: 'thinking',
  },
  suspicious: {
    key: 'suspicious',
    label: 'Suspicious',
    emoji: '🤨',
    extraEmojis: ['🧐', '👀'],
    expression: 'narrowed eyes glancing sideways, tight mouth',
    pose: 'arms crossed',
    base: 'sigma',
  },
  smug: {
    key: 'smug',
    label: 'Smug',
    emoji: '😏',
    extraEmojis: ['😼', '😎'],
    expression: 'self-satisfied smirk, half-lidded eyes',
    pose: 'hands on hips',
    base: 'sigma',
  },
  proud: {
    key: 'proud',
    label: 'Proud',
    emoji: '💪',
    extraEmojis: ['😤', '🏆'],
    expression: 'proud closed smile, chin lifted',
    pose: 'flexing both biceps',
    accent: 'sparkles',
    base: 'cool',
  },
  celebrate: {
    key: 'celebrate',
    label: 'Celebrate',
    emoji: '🥳',
    extraEmojis: ['🎉', '🙌'],
    expression: 'joyful open-mouthed cheer, eyes closed happily',
    pose: 'both fists raised in victory',
    accent: 'confetti',
    base: 'laughing',
  },
  excited: {
    key: 'excited',
    label: 'Excited',
    emoji: '🤩',
    extraEmojis: ['✨', '😆'],
    expression: 'big grin with star-shaped sparkling eyes',
    pose: 'fists pumped in excitement',
    accent: 'sparkles',
    base: 'happy',
  },
  starstruck: {
    key: 'starstruck',
    label: 'Starstruck',
    emoji: '🤩',
    extraEmojis: ['⭐', '😍'],
    expression: 'amazed open mouth, star-shaped eyes',
    pose: 'hands on the cheeks in awe',
    accent: 'stars',
    base: 'shocked',
  },
  mindblown: {
    key: 'mindblown',
    label: 'Mind blown',
    emoji: '🤯',
    extraEmojis: ['💥', '😱'],
    expression: 'astonished, jaw dropped, eyes huge',
    pose: 'hands on the sides of the head',
    accent: 'explosion burst',
    base: 'shocked',
  },
  sad: {
    key: 'sad',
    label: 'Sad',
    emoji: '😢',
    extraEmojis: ['😞', '🥺'],
    expression: 'downturned mouth, droopy eyes about to cry',
    pose: 'shoulders slumped',
    accent: 'single tear',
    base: 'crying',
  },
  disappointed: {
    key: 'disappointed',
    label: 'Disappointed',
    emoji: '😞',
    extraEmojis: ['😔', '😒'],
    expression: 'let-down frown, eyes half closed, head lowered',
    pose: 'arms hanging',
    base: 'crying',
  },
  pleading: {
    key: 'pleading',
    label: 'Pleading',
    emoji: '🥺',
    extraEmojis: ['🙏', '😢'],
    expression: 'huge glossy puppy eyes, eyebrows raised, tiny frown',
    pose: 'hands pressed together pleading',
    base: 'crying',
  },
  grateful: {
    key: 'grateful',
    label: 'Grateful',
    emoji: '🙏',
    extraEmojis: ['😊', '💖'],
    expression: 'thankful closed-eye smile',
    pose: 'hands pressed together, slight bow',
    accent: 'sparkles',
    base: 'happy',
  },
  shrug: {
    key: 'shrug',
    label: 'Shrug',
    emoji: '🤷',
    extraEmojis: ['😶', '🙃'],
    expression: 'indifferent smirk, eyebrows raised',
    pose: 'both palms up in a shrug',
    base: 'sigma',
  },
  eyeroll: {
    key: 'eyeroll',
    label: 'Eye roll',
    emoji: '🙄',
    extraEmojis: ['😒', '😑'],
    expression: 'eyes rolled up, flat mouth',
    pose: 'hands on hips',
    base: 'facepalm',
  },
  annoyed: {
    key: 'annoyed',
    label: 'Annoyed',
    emoji: '😒',
    extraEmojis: ['😤', '🙄'],
    expression: 'irritated flat mouth, half-lidded glare',
    pose: 'arms crossed',
    base: 'angry',
  },
  furious: {
    key: 'furious',
    label: 'Furious',
    emoji: '🤬',
    extraEmojis: ['😡', '💢'],
    expression: 'red-faced rage, teeth clenched, brows slammed down',
    pose: 'shaking fists, shoulders tensed',
    accent: 'steam and anger mark',
    base: 'angry',
  },
  evil: {
    key: 'evil',
    label: 'Evil',
    emoji: '😈',
    extraEmojis: ['👿', '🦹'],
    expression: 'sly villainous grin, angled brows, half-lidded eyes',
    pose: 'fingertips pressed together scheming',
    base: 'sigma',
  },
  crazy: {
    key: 'crazy',
    label: 'Crazy',
    emoji: '🤪',
    extraEmojis: ['😜', '🙃'],
    expression: 'goofy face, tongue out, one eye winking',
    pose: 'peace sign',
    base: 'laughing',
  },
  silly: {
    key: 'silly',
    label: 'Silly',
    emoji: '😛',
    extraEmojis: ['😝', '😜'],
    expression: 'playful tongue out, eyes squinting with fun',
    pose: 'peace sign',
    base: 'happy',
  },
  yummy: {
    key: 'yummy',
    label: 'Yummy',
    emoji: '😋',
    extraEmojis: ['🤤', '🍕'],
    expression: 'licking lips with tongue, happy closed eyes',
    pose: 'rubbing the belly',
    base: 'happy',
  },
  money: {
    key: 'money',
    label: 'Money',
    emoji: '🤑',
    extraEmojis: ['💸', '💰'],
    expression: 'greedy grin with dollar-sign eyes',
    pose: 'thumbs up',
    accent: 'floating coins',
    base: 'cool',
  },
  dead: {
    key: 'dead',
    label: 'Dead',
    emoji: '😵',
    extraEmojis: ['💀', '🥴'],
    expression: 'knocked out, X-shaped eyes, tongue out, pale',
    pose: 'arms hanging limp',
    base: 'facepalm',
  },
  dizzy: {
    key: 'dizzy',
    label: 'Dizzy',
    emoji: '😵‍💫',
    extraEmojis: ['🥴', '💫'],
    expression: 'spiral eyes, wobbly mouth, head tilted',
    pose: 'arms hanging',
    accent: 'orbiting stars',
    base: 'shocked',
  },
  cold: {
    key: 'cold',
    label: 'Cold',
    emoji: '🥶',
    extraEmojis: ['❄️', '🧊'],
    expression: 'freezing blue face, chattering teeth',
    pose: 'hugging himself to keep warm',
    accent: 'snowflakes',
    base: 'shocked',
  },
  hot: {
    key: 'hot',
    label: 'Hot',
    emoji: '🥵',
    extraEmojis: ['🔥', '💦'],
    expression: 'overheated red face, tongue out panting, sweating',
    pose: 'fanning the face with one hand',
    accent: 'sweat drops and flames',
    base: 'shocked',
  },
  shush: {
    key: 'shush',
    label: 'Shush',
    emoji: '🤫',
    extraEmojis: ['🤐', '😶'],
    expression: 'secretive look, lips closed',
    pose: 'index finger pressed to the lips',
    base: 'sigma',
  },
  salute: {
    key: 'salute',
    label: 'Salute',
    emoji: '🫡',
    extraEmojis: ['🎖️', '😤'],
    expression: 'determined friendly smile',
    pose: 'military salute at the brow',
    base: 'cool',
  },
  peace: {
    key: 'peace',
    label: 'Peace',
    emoji: '✌️',
    extraEmojis: ['😁', '🤙'],
    expression: 'big cheerful grin',
    pose: 'peace sign with one hand',
    base: 'happy',
  },
  ok: {
    key: 'ok',
    label: 'OK',
    emoji: '👌',
    extraEmojis: ['🙂', '👍'],
    expression: 'satisfied smile',
    pose: 'OK hand sign',
    base: 'happy',
  },
  thumbsdown: {
    key: 'thumbsdown',
    label: 'Thumbs down',
    emoji: '👎',
    extraEmojis: ['😒', '🙅'],
    expression: 'disapproving frown',
    pose: 'thumbs down',
    base: 'angry',
  },
  clap: {
    key: 'clap',
    label: 'Applause',
    emoji: '👏',
    extraEmojis: ['🙌', '😄'],
    expression: 'delighted grin',
    pose: 'clapping hands',
    base: 'happy',
  },
  hug: {
    key: 'hug',
    label: 'Hug',
    emoji: '🤗',
    extraEmojis: ['🫂', '🥰'],
    expression: 'warm closed-eye smile',
    pose: 'arms wrapped in a big hug',
    accent: 'small hearts',
    base: 'love',
  },
  bye: {
    key: 'bye',
    label: 'Bye',
    emoji: '👋',
    extraEmojis: ['😊', '🙋'],
    expression: 'friendly smile',
    pose: 'waving goodbye',
    base: 'happy',
  },
  idea: {
    key: 'idea',
    label: 'Idea',
    emoji: '💡',
    extraEmojis: ['☝️', '🤓'],
    expression: 'eureka face, eyebrows raised, small open smile',
    pose: 'index finger pointing up',
    accent: 'glowing light bulb',
    base: 'thinking',
  },
  gasp: {
    key: 'gasp',
    label: 'Gasp',
    emoji: '😮',
    extraEmojis: ['😯', '😲'],
    expression: 'small surprised O mouth, wide eyes',
    pose: 'hand covering the mouth',
    base: 'shocked',
  },
  oops: {
    key: 'oops',
    label: 'Oops',
    emoji: '🙊',
    extraEmojis: ['😬', '😅'],
    expression: 'awkward toothy grimace, sweat drop',
    pose: 'hand over the mouth',
    accent: 'sweat drop',
    base: 'shocked',
  },
  party: {
    key: 'party',
    label: 'Party',
    emoji: '🎉',
    extraEmojis: ['🥳', '🎊'],
    expression: 'laughing with joy',
    pose: 'both arms up celebrating',
    accent: 'confetti and streamers',
    base: 'laughing',
  },
};

export function baseEmotion(emotion: string | undefined): BaseEmotion | 'neutral' {
  if (!emotion || emotion === 'neutral') return 'neutral';
  return EMOTION_CATALOG[emotion as StickerEmotion]?.base ?? 'happy';
}

/** Default emotion order; FREE users get the first N (see plans.ts). */
export const DEFAULT_STICKER_ORDER: readonly StickerEmotion[] = [
  'happy',
  'laughing',
  'love',
  'shocked',
  'cool',
  'crying',
  'angry',
  'sigma',
  'thinking',
  'facepalm',
  'joy',
  'rofl',
  'wink',
  'kiss',
  'shy',
  'embarrassed',
  'nervous',
  'scared',
  'terrified',
  'disgusted',
  'sick',
  'sleepy',
  'sleeping',
  'yawning',
  'bored',
  'confused',
  'suspicious',
  'smug',
  'proud',
  'celebrate',
  'excited',
  'starstruck',
  'mindblown',
  'sad',
  'disappointed',
  'pleading',
  'grateful',
  'shrug',
  'eyeroll',
  'annoyed',
  'furious',
  'evil',
  'crazy',
  'silly',
  'yummy',
  'money',
  'dead',
  'dizzy',
  'cold',
  'hot',
  'shush',
  'salute',
  'peace',
  'ok',
  'thumbsdown',
  'clap',
  'hug',
  'bye',
  'idea',
  'gasp',
  'oops',
  'party',
];

/** Size of the pack generated when no emotions are picked explicitly. */
export const DEFAULT_PACK_SIZE = 10;
